version : '3'

services :
  mysql:
    image: mysql:8
    container_name: mysql_service
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --default-authentication-plugin=mysql_native_password
    volumes:
      - ../volumes-mysql/mysql/:/var/lib/mysql/
    environment: 
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "dash"
      MYSQL_USER: "leeway"
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
  web : 
    build :  .
    volumes :
    - ./:/usr/src/app/
    command : python manage.py runserver 0.0.0.0:80
    ports:
    - 80:80
    env_file :
    - ./.env.dev
    depends_on: 
    - mysql


