# Generated by Django 4.0.5 on 2022-06-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arrival_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('label', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='departure_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(db_index=True)),
                ('label', models.CharField(max_length=40)),
            ],
        ),
    ]
