# Generated by Django 4.0.5 on 2022-08-09 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_delete_arrival_info"),
    ]

    operations = [
        migrations.CreateModel(
            name="dodomoaBookInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISBN", models.PositiveIntegerField(db_index=True)),
                ("도서명", models.CharField(max_length=180)),
                ("저자", models.CharField(max_length=240)),
                ("출판사", models.CharField(max_length=50)),
                ("주제분류번호", models.CharField(max_length=20)),
                ("등록일자", models.DateField()),
                ("이미지주소", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="dodomoaKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ISBN", models.PositiveIntegerField(db_index=True)),
                ("key0", models.CharField(max_length=40)),
                ("key1", models.CharField(max_length=40)),
                ("key2", models.CharField(max_length=40)),
                ("key3", models.CharField(max_length=40)),
                ("key4", models.CharField(max_length=40)),
                ("key5", models.CharField(max_length=40)),
                ("key6", models.CharField(max_length=40)),
                ("key7", models.CharField(max_length=40)),
                ("key8", models.CharField(max_length=40)),
                ("key9", models.CharField(max_length=40)),
                ("key10", models.CharField(max_length=40)),
                ("key11", models.CharField(max_length=40)),
                ("key12", models.CharField(max_length=40)),
                ("key13", models.CharField(max_length=40)),
                ("key14", models.CharField(max_length=40)),
                ("key15", models.CharField(max_length=40)),
                ("key16", models.CharField(max_length=40)),
                ("key17", models.CharField(max_length=40)),
                ("key18", models.CharField(max_length=40)),
                ("key19", models.CharField(max_length=40)),
                ("key40", models.CharField(max_length=40)),
                ("key21", models.CharField(max_length=40)),
                ("key22", models.CharField(max_length=40)),
                ("key23", models.CharField(max_length=40)),
                ("key24", models.CharField(max_length=40)),
                ("key25", models.CharField(max_length=40)),
                ("key26", models.CharField(max_length=40)),
                ("key27", models.CharField(max_length=40)),
                ("key28", models.CharField(max_length=40)),
                ("key29", models.CharField(max_length=40)),
                ("key30", models.CharField(max_length=40)),
                ("key31", models.CharField(max_length=40)),
                ("key32", models.CharField(max_length=40)),
                ("key33", models.CharField(max_length=40)),
                ("key34", models.CharField(max_length=40)),
                ("key35", models.CharField(max_length=40)),
                ("key36", models.CharField(max_length=40)),
                ("key37", models.CharField(max_length=40)),
                ("key38", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="dodomoaLibInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("지역", models.CharField(max_length=5)),
                ("ISBN", models.PositiveIntegerField()),
            ],
        ),
    ]
