# Generated by Django 4.0.5 on 2022-08-09 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_dodomoabookinfo_dodomoakeyword_dodomoalibinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodomoabookinfo',
            name='ISBN',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='ISBN',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dodomoalibinfo',
            name='ISBN',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
