# Generated by Django 4.0.5 on 2022-08-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_dodomoabookinfo_isbn_alter_dodomoakeyword_isbn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dodomoakeyword',
            old_name='key40',
            new_name='key20',
        ),
    ]
