# Generated by Django 4.0.5 on 2022-08-09 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_rename_key40_dodomoakeyword_key20'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key0',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key10',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key11',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key12',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key13',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key14',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key15',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key16',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key17',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key18',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key19',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key20',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key21',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key22',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key23',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key24',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key25',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key26',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key27',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key28',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key29',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key3',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key30',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key31',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key32',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key33',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key34',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key35',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key36',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key37',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key38',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key5',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key6',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key7',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key8',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='dodomoakeyword',
            name='key9',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
